" clear any existing auto commands
autocmd!

syntax on
filetype on
colorscheme pablo
" colorscheme delek

" make searches case insensitive:
set ignorecase
set smartcase

" show the best match so far as search strings are typed:
set incsearch

" setting 100 lines of commandline history:
set history=1000

" don't have files attempting to override this .vimrc:
set nomodeline

" don't make it look line there are line breaks were there aren't:
set nowrap

" use indents of 4 spaces, and have them copied down lines:
set tabstop=4
set shiftwidth=4 smarttab
set softtabstop=0 noexpandtab
set expandtab

" syntax:
set syntax=ah
set hlsearch

" normally don't automatically format `text' as it is typed, IE only do this
" with comments, at 79 characters:
set formatoptions-=t
set textwidth=79

" autoindentation
set autoindent

autocmd BufRead,BufWritePre *.sh normal gg=G
